class Member {
  final String name;
  final String team;
  final String role;
  final int years;
  final String phone;
  final String email;
  final String employeeId;
  final String department;
  final String reportingManager;
  final String dateOfHire;
  final String employmentType;
  final String salaryOrPayRate;
  final String compensationStructure;
  final String benefitsEnrollment;
  final String address;
  final String emergencyContactName;
  final String emergencyContactRelationship;
  final String emergencyContactNumber;
  final String alternateNumber;

  Member({
    required this.name,
    required this.team,
    required this.role,
    required this.years,
    required this.phone,
    required this.email,
    required this.employeeId,
    required this.department,
    required this.reportingManager,
    required this.dateOfHire,
    required this.employmentType,
    required this.salaryOrPayRate,
    required this.compensationStructure,
    required this.benefitsEnrollment,
    required this.address,
    required this.emergencyContactName,
    required this.emergencyContactRelationship,
    required this.emergencyContactNumber,
    required this.alternateNumber,
  });
}

final List<Member> members = [
  Member(
    name: 'Alice Johnson',
    role: 'Software Engineer',
    years: 3,
    team: 'Development Team A',
    phone: '+1 (555) 123-4567',
    email: 'alice@example.com',
    employeeId: '001',
    department: 'Engineering',
    reportingManager: 'John Manager',
    dateOfHire: '2022-05-15',
    employmentType: 'Full-Time',
    salaryOrPayRate: '85000',
    compensationStructure: 'Salary',
    benefitsEnrollment: 'Health Insurance, 401(k)',
    address: '123 Main St, City, State',
    emergencyContactName: 'Bob Johnson',
    emergencyContactRelationship: 'Spouse',
    emergencyContactNumber: '+1 (555) 987-6543',
    alternateNumber: '+1 (555) 111-2222',
  ),
  Member(
    name: 'Bob Smith',
    role: 'Frontend Developer',
    years: 2,
    team: 'UI/UX Team',
    phone: '+1 (555) 987-6543',
    email: 'bob@example.com',
    employeeId: '002',
    department: 'UI/UX Design',
    reportingManager: 'Laura Manager',
    dateOfHire: '2022-03-10',
    employmentType: 'Full-Time',
    salaryOrPayRate: '75000',
    compensationStructure: 'Salary',
    benefitsEnrollment: 'Health Insurance',
    address: '456 Elm St, City, State',
    emergencyContactName: 'Ella Smith',
    emergencyContactRelationship: 'Spouse',
    emergencyContactNumber: '+1 (555) 123-4567',
    alternateNumber: '+1 (555) 222-3333',
  ),
  Member(
    name: 'Bob Smith',
    role: 'Frontend Developer',
    years: 2,
    team: 'UI/UX Team',
    phone: '+1 (555) 987-6543',
    email: 'bob@example.com',
    employeeId: '002',
    department: 'UI/UX Design',
    reportingManager: 'Laura Manager',
    dateOfHire: '2022-03-10',
    employmentType: 'Full-Time',
    salaryOrPayRate: '75000',
    compensationStructure: 'Salary',
    benefitsEnrollment: 'Health Insurance',
    address: '456 Elm St, City, State',
    emergencyContactName: 'Ella Smith',
    emergencyContactRelationship: 'Spouse',
    emergencyContactNumber: '+1 (555) 123-4567',
    alternateNumber: '+1 (555) 222-3333',
  ),
  Member(
    name: 'Bob Smith',
    role: 'Frontend Developer',
    years: 2,
    team: 'UI/UX Team',
    phone: '+1 (555) 987-6543',
    email: 'bob@example.com',
    employeeId: '002',
    department: 'UI/UX Design',
    reportingManager: 'Laura Manager',
    dateOfHire: '2022-03-10',
    employmentType: 'Full-Time',
    salaryOrPayRate: '75000',
    compensationStructure: 'Salary',
    benefitsEnrollment: 'Health Insurance',
    address: '456 Elm St, City, State',
    emergencyContactName: 'Ella Smith',
    emergencyContactRelationship: 'Spouse',
    emergencyContactNumber: '+1 (555) 123-4567',
    alternateNumber: '+1 (555) 222-3333',
  ),
  Member(
    name: 'Bob Smith',
    role: 'Frontend Developer',
    years: 2,
    team: 'UI/UX Team',
    phone: '+1 (555) 987-6543',
    email: 'bob@example.com',
    employeeId: '002',
    department: 'UI/UX Design',
    reportingManager: 'Laura Manager',
    dateOfHire: '2022-03-10',
    employmentType: 'Full-Time',
    salaryOrPayRate: '75000',
    compensationStructure: 'Salary',
    benefitsEnrollment: 'Health Insurance',
    address: '456 Elm St, City, State',
    emergencyContactName: 'Ella Smith',
    emergencyContactRelationship: 'Spouse',
    emergencyContactNumber: '+1 (555) 123-4567',
    alternateNumber: '+1 (555) 222-3333',
  ),
  Member(
    name: 'Bob Smith',
    role: 'Frontend Developer',
    years: 2,
    team: 'UI/UX Team',
    phone: '+1 (555) 987-6543',
    email: 'bob@example.com',
    employeeId: '002',
    department: 'UI/UX Design',
    reportingManager: 'Laura Manager',
    dateOfHire: '2022-03-10',
    employmentType: 'Full-Time',
    salaryOrPayRate: '75000',
    compensationStructure: 'Salary',
    benefitsEnrollment: 'Health Insurance',
    address: '456 Elm St, City, State',
    emergencyContactName: 'Ella Smith',
    emergencyContactRelationship: 'Spouse',
    emergencyContactNumber: '+1 (555) 123-4567',
    alternateNumber: '+1 (555) 222-3333',
  ),
];
